### ISSUE TITLE
A way to close the craft menu by f1-clicking to select your hero?

### ISSUE THREAD

**Issue by muhshi4** [Vendivar/IslandTrollTribes2#131]
It's slightly annoying to always have to click on the ground when you want to close the item craft menu. Is it possible to make it work like the dota2 shop where it's closed when you press the hotkey for your hero.

**Comment by MNoya** [comment]
You can press the hotkey for crafting (C) as a toggle instead.

**Comment by muhshi4** [comment]
I mean the popup window when you want to craft a item in a building, the only way to close it is click on the ground. Would be nice if there was a hotkey for closing that.

**Comment by MNoya** [comment]
Yeah I can see how that can be annoying. Problem is, the Dota shop closes on selection, but for the crafting panels I couldn't do that because I think you have to be able to select your teammate to see their items (if they have an ingredient for a recipe you are working on, for example). I can try making it so that if the player hero gets selected twice in a row, then it closes.

**Comment by MNoya** [comment]
enjoy @muhshi4
