### ISSUE TITLE
Death with PanicBuff enabled makes you relive with PanicBuff with infinite duration

### ISSUE THREAD

**Issue by Dillerfax** [Vendivar/IslandTrollTribes2#135]

**Comment by Dli42** [comment]
I believe I fixed this a while ago, but I'll check again.

**Comment by MNoya** [comment]
So the problem was that modifier_panic was "Passive" "1".

In the toolkit lua, the process to use Panic is: Teach the "panic" ability if the user doesn't have it, then cast it. I can see some potential bugs with this approach, such as running out of ability slots or forgetting cooldown. Ideally the modifier should be applied directly without the ability, and the sound/

**Comment by Dli42** [comment]
Ok, that makes a lot of sense
