### ISSUE TITLE
Craft master in the center that crafts the troll 6 slot recipies

### ISSUE THREAD

**Issue by Vendivar** [Vendivar/IslandTrollTribes2#157]
Should be pretty easy we can make it just have the abilities it needs to craft the few things it needs to craft to have or give it a crafting panel. It needs to be able to be used by any team though

**Comment by MNoya** [comment]
http://islandtrolltribes.wikia.com/wiki/Craftmaster

This shares all the entries from "Recipes" list, right? Should totally be a crafting panel associated with it. 

We need to make it be shared to both teams in order for them to take the items out of the crafter (otherwise a team could block the usage of it by dragging useless items onto it). This can get messy if more than one team is on the area.

How about we make it a **First Come-First Served** style of building in which the first player to enter the area sets the ownership and share-ability of the building while inside its usage radius. If another player from an enemy team comes near, they will have to kill the players who were in possession of the building earlier.

**Comment by Vendivar** [comment]
That sounds great!

**Comment by MNoya** [comment]
Need to put an info_target on both maps to point where it needs to be placed, I will leave that to you @Vendivar
