### ISSUE TITLE
Hotkey "H" prevents standard hold-position hotkey

### ISSUE THREAD

**Issue by MNoya** [Vendivar/IslandTrollTribes2#262]
Maybe the Help panel should become "Info" with **i** as a hotkey?

**Comment by Vendivar** [comment]
Does hold matter though when S is stop

**Comment by MNoya** [comment]
I like holding my hero when testing so it doesn't run off, perhaps its not that much of a deal for real game though. That said, the "i" panel should now be gone, right?

**Comment by Vendivar** [comment]
It couldn't hurt. As it was now the I didn't auto hide
Since there's a help menu now I don't see why it should stay after loading.

**Comment by Vendivar** [comment]
I still want to call it help because information to me could give players
the sense that it's less urgent to read it

On Jul 31, 2016 5:25 PM, "Vendivar ." <vendivar@gmail.com> wrote:

It couldn't hurt. As it was now the I didn't auto hide
Since there's a help menu now I don't see why it should stay after loading.

**Comment by Vendivar** [comment]
Changed to "L"
